# Generated by Django 5.0.4 on 2024-05-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url_image',
            field=models.CharField(default='url', max_length=255),
        ),
    ]
